config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  post "likes/:recipe_id/create", to: "likes#create"
  delete "likes/:recipe_id/destroy", to: "likes#destroy"
  resources :recipes do
    collection do
      get 'search', 'order'
    end
    member do
      get 'user'
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :image
    validates :title, length: { maximum: 20 }
    validates :price
    validates :procedure1
    validates_inclusion_of :price, in: 1..1000, message: 'Out of setting range'
  end

  with_options length: { maximum: 50 } do
    validates :procedure1
    validates :procedure2
    validates :procedure3
  end

  def self.search(search)
    if search != ''
      Recipe.where('title LIKE(?)', "%#{search}%").order('created_at DESC')
    else
      Recipe.includes(:user).order('created_at DESC')
    end
  end

  def self.ave(recipe)
    price = 0
    recipe.each do |recipe|
      price += recipe.price
    end
    price / recipe.length
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :user, :new_order]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :identification, only: [:edit, :update, :destroy]
  before_action :get_recipe, only: [:index, :order]

  def index
    @recipe_pop = Recipe.includes(:liked_users, :likes, :user).sort { |a, b| b.liked_users.size <=> a.liked_users.size }
    @recipe_price = Recipe.includes(:user, :likes).order('price ASC')
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.valid?
      @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def search
    @recipe = Recipe.search(params[:keyword])
  end

  def user
    @user = User.find(params[:id])
    @recipe = @user.recipes
    @price = Recipe.ave(@recipe)
    @like_count = Like.count(@user)
  end

  def order
  end

  private

  def get_recipe
    @recipe = Recipe.includes(:user, :likes).order('created_at DESC')
  end

  def recipe_params
    params.require(:recipe).permit(:image, :title, :price, :procedure1, :procedure2, :procedure3,
                                   :info).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def identification
    redirect_to root_path unless current_user.id == @recipe.user_id
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<%# cssはrecipe/new.cssを使用 %>

<div class="new-recipe-contens">
  <header class="new-recipe-header">
     <%= link_to image_tag("kyo_rogo.png", class:"logo-image"), "/" %>
  </header>


  <div class="new-recipe-main">
    <div class="new-recipe-title">レシピを更新</div>

    <%= form_with model: @recipe, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="input-field">
      <%= f.label :画像：必須 %><br />
      <%= f.file_field :image %>
    </div>

    <div class="input-field">
      <%= f.label :タイトル：必須 %><br />
      <%= f.text_field :title, placeholder: "20文字以内で記入してください"  %>
    </div>

    <div class="input-field">
      <%= f.label :材料費：必須 %><br />
      <%= f.text_field :price, placeholder: "1000(円)以内で記入してください"  %>
    </div>

    <div class="input-field">
      <%= f.label :手順①：必須 %><br />
      <%= f.text_field :procedure1, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :手順② %><br />
      <%= f.text_field :procedure2, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :手順③ %><br />
      <%= f.text_field :procedure3, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :コツ・ポイント・補足 %><br />
      <%= f.text_area :info, size: "50%" %>
    </div>

    <%= f.submit "更新する" ,class:"sell-btn" %>

  <% end %>
</div>

app/views/recipes/index.html.erb
<%= render "shared/header" %>
<%# _heder.htmlcss使用 %>
<div class='header-anker'>
</div>  
<div class="top-main">
  <div class='title-contents'>
    <div class='title-text'>
      KYOレシピ検索アプリ！
    </div>
    <p class='title-sub-text'>
        簡単で、安くて、美味しい！<br>『今日』作れるものがすぐに見つかる！
    </p>
    <div class="rule-contents">
      <ul class="rule-title">
      〜KYOレシピの3つの特徴〜
        <li class="rule-list">
        「K」簡単に作れる。手順は3つまで、1つ50文字以内でできるもの。
        </li>
        <li class="rule-list"> 
        「Y」安く出来る。金額は一人分の作成費、最大1000円まで。
        </li>
        <li class="rule-list"> 
        「O」美味しいもの。見た目よりも美味しさ重視。
        </li>
      </ul>
    </div>
  </div>
  <div class="recipe-contents">
    <div class="recipe-list-title">
      新着レシピ（新着順）
      <%= link_to "〜新着順レシピはこちら〜", order_recipes_path, class: "recipe-order-link" %>
    </div>
    <div class="recipe-lists">
      <% @recipe.first(3).each do |recipe| %>
        <%= render partial: "shared/recipe_list", locals: { recipe: recipe } %>
      <% end %>
    </div>
    <div class="recipe-list-title">
      人気レシピ TOP3!
    </div>
    <div class="recipe-lists">
      <% @recipe_pop.first(3).each do |recipe| %>
        <%= render partial: "shared/recipe_list", locals: { recipe: recipe } %>
      <% end %>
    </div>
    <div class="recipe-list-title">
      激安レシピ TOP3!
    </div>
    <div class="recipe-lists">
      <% @recipe_price.first(3).each do |recipe| %>
        <%= render partial: "shared/recipe_list", locals: { recipe: recipe } %>
      <% end %>
    </div>
  </div> 
</div>

app/views/recipes/new.html.erb
<div class="new-recipe-contens">
  <header class="new-recipe-header">
     <%= link_to image_tag("kyo_rogo.png", class:"logo-image"), "/" %>
  </header>


  <div class="new-recipe-main">
    <div class="new-recipe-title">レシピを投稿</div>

    <%= form_with model: @recipe, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="input-field">
      <%= f.label :画像：必須 %><br />
      <%= f.file_field :image %>
    </div>

    <div class="input-field">
      <%= f.label :タイトル：必須 %><br />
      <%= f.text_field :title, placeholder: "20文字以内で記入してください"  %>
    </div>

    <div class="input-field">
      <%= f.label :材料費：必須 %><br />
      <%= f.text_field :price, placeholder: "半角数字、1000(円)以内で記入してください"  %>
    </div>

    <div class="input-field">
      <%= f.label :手順①：必須 %><br />
      <%= f.text_field :procedure1, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :手順② %><br />
      <%= f.text_field :procedure2, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :手順③ %><br />
      <%= f.text_field :procedure3, placeholder: "50文字以内で記入してください" %>
    </div>

    <div class="input-field">
      <%= f.label :コツ・ポイント・補足 %><br />
      <%= f.text_area :info, size: "50%" %>
    </div>

    <%= f.submit "投稿する" ,class:"sell-btn" %>

  <% end %>
</div>

app/views/recipes/order.erb
<%= render "shared/header" %>
<%# _heder.htmlcss使用 %>
<div class='header-anker'>
</div>  

<div class="recipe-contents">
    <div class="recipe-list-title">
      新着レシピ (全件表示）
    </div>
    <div class="recipe-lists">
      <% @recipe.first(12).each do |recipe| %>
        <%= render partial: "shared/recipe_list", locals: { recipe: recipe } %>
      <% end %>
    </div>

app/views/recipes/search.html.erb
<%= render "shared/header" %>
<%# _heder.htmlcss使用 %>
<div class='header-anker'>
</div>  

  <%# recipe/index.scss使用 %>
  <div class="recipe-contents">
    <div class="recipe-list-title">
      検索レシピ（新着順）
    </div>
    <div class="recipe-lists">
      <% @recipe.each do |recipe| %>
        <div class="recipe-list">
          <div class="list-title">
            <%= recipe.title %>
          </div>
          <div class="list-image-box">
            <%= link_to image_tag(recipe.image, class: "list-image"), recipe_path(recipe.id) %>
          </div>
          <div class="list-user-like-price">
            <div class="list-user">
              <%= link_to "#{recipe.user.nickname}",  user_recipe_path(recipe.user_id), class: "list-user-text" %>さん
            </div>
            <div class="list-price">
              約<%= recipe.price%>円
            </div>
            <% if recipe.likes.exists? %>
              <div class="list-like">
                いい値!  <%= recipe.likes.length%>  
              </div>
            <% end %>
          </div>
          <div class="list-procedure">
              <p>〜手順①〜</p>
            <%= recipe.procedure1 %>
            <%= link_to "詳細", recipe_path(recipe.id), class: "procedure-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div> 

app/views/recipes/show.html.erb
<%= render "shared/header" %>
<%# _heder.htmlcss使用 %>
<div class='header-anker'>
</div> 

<div class="recipe-show">
  <div class="recipe-conetent">
    <div class="content-user">
      <%= link_to "#{@recipe.user.nickname}さんのKYOレシピ",  user_recipe_path(@recipe.user_id), class: "content-user-text" %>
      <% if user_signed_in?  && current_user.id == @recipe.user_id %>
        <div class="link-buttons">
          <%= link_to "更新", edit_recipe_path(@recipe.id), class:"link-button" %>
          <%= link_to "削除", recipe_path(@recipe.id), method: :delete, class:"link-button", data: { confirm: "削除したデータは戻りません、よろしいですか？"} %>
        </div>
      <% end %>
    </div>
    <div class="content-image">
      <%= image_tag @recipe.image %>
    </div>
    <div class="contents-like-price">
      <div class="content-like", id="recipe-like">
        <%= render partial: "shared/like", locals: { recipe: @recipe } %>
      </div>
      <div class="content-price">
        （一人分）だいたい<b class="price" ><%= " #{@recipe.price}円" %></b> くらい
      </div>
    </div>
  </div>
  <div class="procedure-content">
    <div class="procedure-box">
      <div class="procedure-num">
        〜手順①〜
      </div>
      <div class="procedure-text">
        <%= @recipe.procedure1 %>
      </div>
    </div>
    <% unless @recipe.procedure2 == "" %>
      <div class="procedure-box">
        <div class="procedure-num">
          〜手順②〜
        </div>
        <div class="procedure-text">
          <%= @recipe.procedure2 %>
        </div>
      </div>
    <% end %>
    <% unless @recipe.procedure3 == "" %>
      <div class="procedure-box">
        <div class="procedure-num">
          〜手順③〜
        </div>
        <div class="procedure-text">
          <%= @recipe.procedure3 %>
        </div>
      </div>
    <% end %>
    <div class="recipe-point-contet">
      <div class="point-title">
        ■コツ・ポイント・補足■
      </div>
      <div class="point-text">
        <%= @recipe.info %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/user.html.erb
<%= render "shared/header" %>
<%# _heder.htmlcss使用 %>
<div class='header-anker'>
</div>  

<div>
  <ul class="user-contens">
    <li class="user-content">
      <%= @user.nickname %>さんのレシピ
    </li>
    <li class="user-content">
      投稿数<%= @recipe.length%>回
    </li>
  </ul>
  <ul class="user-contens">
    <li class="user-content">
      平均費用<%= @price %>円
    </li>
    <li class="user-content">
      総「いい値！」<%= @like_count %>回
    </li>
  </ul>
</div>

  <%# recipe/index.scss使用 %>
  <div class="recipe-contents">
    <div class="recipe-list-title">
      レシピ（新着順）
    </div>
    <div class="recipe-lists">
      <% @recipe.reverse_each do |recipe| %>
        <div class="recipe-list">
          <div class="list-title">
            <%= recipe.title %>
          </div>
          <div class="list-image-box">
            <%= link_to image_tag(recipe.image.variant(resize:'640x480').processed, class: "list-image"), recipe_path(recipe.id) %>
          </div>
          <div class="list-user-like-price">
            <div class="list-user">
              <%= link_to "#{recipe.user.nickname}",  user_recipe_path(recipe.user_id), class: "list-user-text" %>さん
            </div>
            <div class="list-price">
              約<%= recipe.price%>円
            </div>
            <% if recipe.likes.exists? %>
              <div class="list-like">
                いい値!  <%= recipe.likes.length%>  
              </div>
            <% end %>
          </div>
          <div class="list-procedure">
              <p>〜手順①〜</p>
            <%= recipe.procedure1 %>
            <%= link_to "詳細", recipe_path(recipe.id), class: "procedure-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div> 