config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  post "likes/:recipe_id/create", to: "likes#create"
  delete "likes/:recipe_id/destroy", to: "likes#destroy"
  resources :recipes do
    collection do
      get 'search', 'order'
    end
    member do
      get 'user'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>

  <div class='nav'>
    <div class="logo-image-box">
      <%= link_to image_tag("kyo_rogo.png", class:"logo-image"), "/" %>
    </div>
    <div class="nav-right-box">
      <div class="recipe-post" >
        <%= link_to "レシピを投稿する", new_recipe_path, class:"recipe-post-button" %>
      </div>
      <ul class='nav-right'>
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.nickname}さん", edit_user_registration_path, class: "user-nickname" %></li> 
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class='search-bar-contents'>
    <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "タイトルから探す", class: "input-box"%>
      <%= f.submit"検索", class: "search-button" %>
    <% end %>
  </div>
</header>

app/views/shared/_like.html.erb
<% if user_signed_in? %>
  <% if Like.find_by(user_id: current_user.id, recipe_id: recipe.id) %>
    <div class="content-like-done"  >
    <%= link_to "いい値!(済)", "/likes/#{recipe.id}/destroy", method: "delete", remote: true, class:"content-like-done"  %>
    </div>
  <% else %>
    <div class="content-like-not", id="like-not">
    <%= link_to "いい値！", "/likes/#{recipe.id}/create", method: "post", remote: true %>
    </div>
  <% end %>
<% else %>
  <div class="content-like-not">
    <%= link_to "いい値！", new_user_session_path %>
    <div class="login-need">※要ログイン※</div>
  </div>
<% end %>

app/views/shared/_recipe_list.erb
<div class="recipe-list">
  <div class="list-title">
    <%= recipe.title %>
  </div>
  <div class="list-image-box">
    <%= link_to image_tag(recipe.image.variant(resize:'640x480').processed), recipe_path(recipe.id) %>
  </div>
  <div class="list-user-like-price">
    <div class="list-user">
      <%= link_to "#{recipe.user.nickname}",  user_recipe_path(recipe.user_id), class: "list-user-text" %>さん
    </div>
    <div class="list-price">
      約<%= recipe.price%>円
    </div>
    <% if recipe.likes.exists? %>
      <div class="list-like">
        いい値!  <%= recipe.likes.length%>  
      </div>
    <% end %>
  </div>
  <div class="list-procedure">
      <p>〜手順①〜</p>
    <%= recipe.procedure1 %>
    <%= link_to "詳細", recipe_path(recipe.id), class: "procedure-link" %>
  </div>
</div>